# Model Selection and Multimodel Inference {#moddelection}


## WHEN AND WHY WE SELECT MODELS AND WHY THIS IS DIFFICULT
Model selection and multimodel inference are delicate topics! During the data analysis process we sometimes come to a point where we have more than one model that adequately describes the data (Chapters 6 and 10), and that are potentially interpretable in a sensible way. The more complex a model is, the better it fits the data and residual plots (Chapter 6) and predictive model checking (Chapter 10) look even better. But, at what point do we want to stop adding complexity? There is no unique answer to this question, except that the choice of a model is central to science, and that this choice may be based on mathematical criteria and/or on expert knowledge (e.g., Gelman & Rubin, 1995, 1999; Anderson, 2008; Claeskens & Hjort, 2008; Link & Barker, 2010; Gelman et al., 2014; and many more). Biologists should build biologically meaningful models based on their experience of the subject. Consequently, thinking about the processes that have generated the data is a central aspect of model selection.


