# Visualizations {#figures}

## Short Checklist for figures
1. The figure should represent the answer to the study question. Often, the classical types of plots such as a scatterplot, a bar plot, or an effects plot are sufficient. However, in many cases, adding a little bit of creativity can greatly
improve readability or the message of the figure.

2.Label the x- and y-axes. Make sure that the units are indicated either within
the title or in the figure legend.

3. Starty-axisatzeroifthereferencetozeroisimportantfortheinterpretationof
effects. The argument ylim[c(0, max(dat$y)) in R is used for this
purpose.

4. Scale the axes so that all data are shown. Make sure that sample size is
indicated either in the figure or in the legend (or, at least, easy to find in the
text).

5. Use interpretable units. That means, if the variable on the x-axis has been
z-transformed to fit the model, back-transform the effects to the original scale.

6. Give the raw data whenever possible. Sometimes, a significant effect cannot be seen in the raw data because so many other variables have an influence on the outcome. Then, you may prefer showing the effect only (e.g., a regression line with a credible interval) and give the residual standard deviation in the figure legend. Even then, we think it is important to show the raw data graphically somewhere else in the paper or in the supplementary material. A scatterplot of the data can contain structures that are lost in summary statistics.

7. Draw the figures as simply as possible. Avoid 3D graphics. Delete all unnecessary elements.

8. Reduce the number of different colors to a minimum necessary. A color scale from orange to blue gives a gray scale in a black-and-white print. `colorRampPalette(c("orange", "blue"))(5)` produces five colors on a scale from orange to blue. Remember that around 8% of the northern European male population have difficulties distinguishing red from green but it is easier for them to distinguish orange from blue.

## Further reading {-}
- [Data Visualization. A practical introduction](https://socviz.co): A practical introduction to data visulization in R. Good data visualizations also make it easier to communicate your ideas and findings to other people. Beyond that, producing effective plots from your own data is the best way to develop a good eye for reading and understanding graphs—good and bad—made by others.

- [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/): A guide to making visualizations that accurately reflect the data, tell a story, and look professional. […] This is an online preview of the book “Fundamentals of Data Visualization” to be published with O’Reilly Media, Inc. Completed chapters will be posted here as they become available. The book is meant as a guide to making visualizations that accurately reflect the data, tell a story, and look professional. It has grown out of my experience of working with students and postdocs in my laboratory on thousands of data visualizations. 



